terraform {
  # Set-up the remote storage for the state file generated by this terraform project
  backend "s3" {
    region = "us-east-1"
    key = "terraform.tfstate"
    bucket = "jdss3bucket2001"
  }
}